server:
  port: 9010
spring:
  profiles:
    active: dev
  application:
    name: nlp-server
  cloud:
    config:
      fail-fast: true
      discovery:
        service-id: config-server
        enabled: true
      profile: ${spring.profiles.active}
      label: master
  jackson:
    default-property-inclusion: non_empty
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    restart:
      enabled: false
logging:
  level:
    ROOT: INFO
eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
#开启Hystrix
feign:
  hystrix:
    enabled: true
