server:
  port: 8010
spring:
  profiles:
    active: dev
  application:
    name: case-server
  cloud:
    config:
      fail-fast: true
      discovery:
        service-id: config-server
        enabled: true
      profile: ${spring.profiles.active}
      label: master
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true
